sudo: true


install:
    - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
    - mkdir yona
    - bash shell/yona.sh build
    - bash shell/yona.sh init
    - bash shell/yona.sh stop
    - bash shell/yona.sh rm
