language: bash
# sudo: required
dist: trusty

install:
  - git clone https://github.com/saltfactory/docker-yobi.git ~/dockers/docker-yobi

script:
  - cd ~/dockers/docker-yobi; bash build.sh
  - cd ~/dockers/docker-yobi; bash start.sh
